# -*- coding: utf-8 -*-
"""primeproj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CBND_-ljCizKozs9IGa1Yl_BWY6mY5Dl

# Object Detection + Segmentation + Metric Depth + 3-D

**Pipeline:** YOLOv8 -> SAM -> Apple Depth Pro -> Euclidean distance (metres) -> Plotly 3-D

## Steps
| # | Action |
|---|--------|
| 1 | Run **Cell 1** (installs packages). Wait until it prints *Installation complete*. |
| 2 | **Runtime -> Restart session** |
| 3 | **Skip Cell 1** and run **Cell 2** (downloads model checkpoints, ~2.9 GB total) |
| 4 | Run **Cell 3** (loads models) |
| 5 | Run remaining cells in order |

> Set runtime to **GPU**: Runtime -> Change runtime type -> T4 GPU
"""

# Run this cell once, then restart the runtime.
# After restarting, SKIP this cell and start from Cell 2.

# 1) Upgrade ultralytics (Colab may have an old version)
!pip install -q -U ultralytics

# 2) Segment Anything Model
!pip install -q git+https://github.com/facebookresearch/segment-anything.git

# 3) Apple Depth Pro
!pip install -q git+https://github.com/apple/ml-depth-pro.git

# 4) Restore numpy 2.x -- depth-pro/SAM deps may have downgraded it,
#    which breaks Colab's torch (built against numpy 2.x).
!pip install -q 'numpy>=2.0,<3.0' --force-reinstall

print()
print('=' * 55)
print('  Installation complete.')
print('  NOW: Runtime -> Restart session')
print('  Then skip this cell and run Cell 2.')
print('=' * 55)

import os

os.makedirs('checkpoints', exist_ok=True)

# SAM ViT-B  (~375 MB)
if not os.path.exists('checkpoints/sam_vit_b_01ec64.pth'):
    print('Downloading SAM ViT-B (~375 MB) ...')
    ret = os.system(
        'wget -q --show-progress '
        '-O checkpoints/sam_vit_b_01ec64.pth '
        'https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth'
    )
    print('SAM done.' if ret == 0 else 'SAM download FAILED (check network).')
else:
    print('SAM checkpoint already present.')

# Apple Depth Pro  (~2.5 GB)
if not os.path.exists('checkpoints/depth_pro.pt'):
    print('Downloading Depth Pro (~2.5 GB) ...')
    ret = os.system(
        'wget -q --show-progress '
        '-O checkpoints/depth_pro.pt '
        'https://ml-site.cdn-apple.com/models/depth-pro/depth_pro.pt'
    )
    print('Depth Pro done.' if ret == 0 else 'Depth Pro download FAILED.')
else:
    print('Depth Pro checkpoint already present.')

print('All checkpoints ready.')

import torch
import numpy as np
import cv2
from PIL import Image as PILImage
import matplotlib.pyplot as plt
from IPython.display import display, clear_output

# ---- YOLO ----------------------------------------------------------------
from ultralytics import YOLO
YOLO_WEIGHTS = 'yolov8n.pt'   # swap to yolov8s/m/l/x for better accuracy
YOLO_CONF    = 0.25
print(f'Loading YOLOv8 ({YOLO_WEIGHTS}) ...')
yolo_model = YOLO(YOLO_WEIGHTS)
print('YOLOv8 ready.')

# ---- SAM -----------------------------------------------------------------
from segment_anything import sam_model_registry, SamPredictor
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Loading SAM vit_b on {device} ...')
_sam = sam_model_registry['vit_b'](checkpoint='checkpoints/sam_vit_b_01ec64.pth')
_sam.to(device)
sam_predictor = SamPredictor(_sam)
print('SAM ready.')

# ---- Depth Pro -----------------------------------------------------------
import depth_pro as _dp
precision = torch.half if device == 'cuda' else torch.float32
print(f'Loading Depth Pro on {device} ...')
dp_model, dp_transform = _dp.create_model_and_transforms(
    device=device, precision=precision
)
_state = torch.load('checkpoints/depth_pro.pt',
                    map_location=device, weights_only=False)
dp_model.load_state_dict(_state)
dp_model.eval()
print('Depth Pro ready.')

print(f'\nAll models loaded on {device}.')
print(f'torch {torch.__version__} | numpy {np.__version__} | cv2 {cv2.__version__}')

import base64
import plotly.graph_objects as go

# --------------------------------------------------------------------------
def decode_b64(b64_str):
    '''Decode a base64 JPEG/PNG data-URL to an RGB numpy array.'''
    if ',' in b64_str:
        b64_str = b64_str.split(',', 1)[1]
    raw = base64.b64decode(b64_str)
    arr = np.frombuffer(raw, np.uint8)
    bgr = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    return cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)

def show_img(img_rgb, title='', figsize=(10, 6)):
    plt.figure(figsize=figsize)
    plt.imshow(img_rgb)
    if title:
        plt.title(title)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

# --------------------------------------------------------------------------
def run_yolo(img_rgb, conf=YOLO_CONF):
    '''Run YOLOv8, return list of detection dicts.'''
    r = yolo_model(img_rgb, conf=conf, verbose=False)[0]
    out = []
    for b in r.boxes:
        out.append({
            'label':      r.names[int(b.cls)],
            'confidence': float(b.conf),
            'bbox':       b.xyxy[0].cpu().numpy().tolist(),  # [x1,y1,x2,y2]
        })
    return out

def draw_boxes(img_rgb, dets):
    out = img_rgb.copy()
    for d in dets:
        x1, y1, x2, y2 = map(int, d['bbox'])
        cv2.rectangle(out, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(out, f"{d['label']} {d['confidence']:.2f}",
                    (x1, max(y1 - 6, 0)), cv2.FONT_HERSHEY_SIMPLEX,
                    0.55, (0, 255, 0), 2)
    return out

# --------------------------------------------------------------------------
def run_sam(img_rgb, dets):
    '''Return one boolean mask (H,W) per detection.'''
    sam_predictor.set_image(img_rgb)
    masks = []
    for d in dets:
        box = np.array(d['bbox'], dtype=float)  # shape (4,)  xyxy
        m, _, _ = sam_predictor.predict(
            point_coords=None,
            point_labels=None,
            box=box,
            multimask_output=False,
        )
        masks.append(m[0].astype(bool))
    return masks

# --------------------------------------------------------------------------
def run_depth(img_rgb):
    '''Return (depth_metres HxW float32, focal_length_px float).'''
    pil  = PILImage.fromarray(img_rgb)
    tens = dp_transform(pil).to(device)
    with torch.no_grad():
        pred = dp_model.infer(tens, f_px=None)
    depth_m = pred['depth'].cpu().numpy().astype(np.float32)
    f_px    = float(pred['focallength_px'])
    return depth_m, f_px

# --------------------------------------------------------------------------
def to_3d(u, v, z, img_hw, f_px):
    h, w  = img_hw
    cx, cy = w / 2.0, h / 2.0
    return (u - cx) * z / f_px, (v - cy) * z / f_px, z

def build_objects(dets, masks, depth_m, f_px):
    '''Merge YOLO detections + SAM masks + Depth Pro into one list.'''
    h, w = depth_m.shape
    objs = []
    for d, mask in zip(dets, masks):
        x1, y1, x2, y2 = d['bbox']
        cx, cy = (x1 + x2) / 2.0, (y1 + y2) / 2.0
        vals   = depth_m[mask]
        z      = float(vals.mean()) if vals.size > 0 else 0.0
        objs.append({
            'label':      d['label'],
            'confidence': d['confidence'],
            'bbox':       d['bbox'],
            'center_px':  (cx, cy),
            'depth_m':    z,
            'xyz':        to_3d(cx, cy, z, (h, w), f_px),
        })
    return objs

print('Helper functions defined.')

from google.colab import files as _colab_files

print('Upload an image (JPG / PNG):')
_up = _colab_files.upload()

if _up:
    _name = list(_up.keys())[0]
    _raw  = list(_up.values())[0]
    _arr  = np.frombuffer(_raw, np.uint8)
    _bgr  = cv2.imdecode(_arr, cv2.IMREAD_COLOR)
    IMAGE = cv2.cvtColor(_bgr, cv2.COLOR_BGR2RGB)
    print(f'Loaded: {_name}  ({IMAGE.shape[1]} x {IMAGE.shape[0]} px)')
    show_img(IMAGE, _name)
else:
    IMAGE = np.full((480, 640, 3), 128, dtype=np.uint8)
    print('No file uploaded -- using grey placeholder.')

print('Running YOLO ...')
dets = run_yolo(IMAGE)
print(f'  {len(dets)} detection(s)')

if not dets:
    print('Nothing detected. Lower YOLO_CONF or try a different image.')
else:
    print('Running SAM ...')
    masks = run_sam(IMAGE, dets)

    print('Running Depth Pro (10-20 s on GPU) ...')
    depth_m, fpx = run_depth(IMAGE)
    print(f'  focal={fpx:.0f} px   depth=[{depth_m.min():.2f}, {depth_m.max():.2f}] m')

    objects = build_objects(dets, masks, depth_m, fpx)

    print('\n' + '=' * 60)
    print(f'  {len(objects)} object(s) detected')
    print('=' * 60)
    for i, o in enumerate(objects):
        x, y, z = o['xyz']
        print(f"  [{i}] {o['label']:<14} "
              f"conf={o['confidence']:.2f}  "
              f"depth={o['depth_m']:.3f} m  "
              f"3D=({x:.3f}, {y:.3f}, {z:.3f})")
    print('=' * 60)

    # Annotated image
    show_img(draw_boxes(IMAGE, dets), 'YOLOv8 detections')

    # Depth map
    _dn = ((depth_m - depth_m.min()) /
           (depth_m.max() - depth_m.min() + 1e-8) * 255).astype(np.uint8)
    show_img(
        cv2.cvtColor(cv2.applyColorMap(_dn, cv2.COLORMAP_PLASMA), cv2.COLOR_BGR2RGB),
        'Depth map  (Apple Depth Pro -- metric metres)'
    )

if len(objects) < 2:
    print('Need at least 2 detected objects to measure distance.')
else:
    A, B = 0, 1   # change these indices to pick different objects

    p1 = np.array(objects[A]['xyz'])
    p2 = np.array(objects[B]['xyz'])
    dist_m  = float(np.linalg.norm(p1 - p2))
    dist_cm = dist_m * 100.0
    print(f"[{A}] {objects[A]['label']}  <->  [{B}] {objects[B]['label']}: "
          f"{dist_m:.4f} m  ({dist_cm:.1f} cm)")

    # Sub-sampled point cloud
    S = 6
    _h, _w = depth_m.shape
    _uu, _vv = np.meshgrid(np.arange(0, _w, S), np.arange(0, _h, S))
    _zz = depth_m[_vv, _uu]
    _cx, _cy = _w / 2.0, _h / 2.0
    _XX = (_uu - _cx) * _zz / fpx
    _YY = (_vv - _cy) * _zz / fpx
    _col = [f'rgb({r},{g},{b})' for r, g, b in IMAGE[_vv, _uu].reshape(-1, 3)]

    def _sphere(centre, colour, name):
        u_ = np.linspace(0, 2 * np.pi, 20)
        v_ = np.linspace(0, np.pi, 20)
        r  = 0.04
        return go.Surface(
            x=centre[0] + r * np.outer(np.cos(u_), np.sin(v_)),
            y=centre[1] + r * np.outer(np.sin(u_), np.sin(v_)),
            z=centre[2] + r * np.outer(np.ones(20), np.cos(v_)),
            colorscale=[[0, colour], [1, colour]],
            showscale=False, name=name, opacity=0.9,
        )

    fig = go.Figure([
        go.Scatter3d(
            x=_XX.ravel(), y=_YY.ravel(), z=_zz.ravel(),
            mode='markers',
            marker=dict(size=1.5, color=_col, opacity=0.5),
            name='scene',
        ),
        _sphere(p1, 'red',  objects[A]['label']),
        _sphere(p2, 'blue', objects[B]['label']),
        go.Scatter3d(
            x=[p1[0], p2[0]], y=[p1[1], p2[1]], z=[p1[2], p2[2]],
            mode='lines+text',
            line=dict(color='lime', width=5),
            text=['', f'{dist_cm:.1f} cm'],
            textposition='top center',
            name='distance',
        ),
    ])
    fig.update_layout(
        title=f"{objects[A]['label']} <-> {objects[B]['label']}: {dist_cm:.1f} cm",
        scene=dict(
            xaxis_title='X (m)',
            yaxis_title='Y (m)',
            zaxis_title='Depth (m)',
        ),
        height=650,
        margin=dict(l=0, r=0, b=0, t=40),
    )
    fig.show()

A, B = 0, 1   # Indices of the two objects

p1 = np.array(objects[A]['xyz'])
p2 = np.array(objects[B]['xyz'])
dist_m  = float(np.linalg.norm(p1 - p2))
dist_cm = dist_m * 100.0

print(f"3D coordinates of object A (bottle): {p1}")
print(f"3D coordinates of object B (bottle): {p2}")
print(f"Distance in meters: {dist_m:.4f} m")
print(f"Distance in centimeters: {dist_cm:.1f} cm")

from google.colab import files as _colab_files
import plotly.io as pio

# Depth map
try:
    _dn = ((depth_m - depth_m.min()) /
           (depth_m.max() - depth_m.min() + 1e-8) * 255).astype(np.uint8)
    cv2.imwrite('depth_map.png', cv2.applyColorMap(_dn, cv2.COLORMAP_PLASMA))
    _colab_files.download('depth_map.png')
    print('depth_map.png downloaded.')
except NameError:
    print('depth_m not available -- run Cell 6 first.')

# Annotated detections
try:
    _ann = draw_boxes(IMAGE, dets)
    cv2.imwrite('detections.png', cv2.cvtColor(_ann, cv2.COLOR_RGB2BGR))
    _colab_files.download('detections.png')
    print('detections.png downloaded.')
except NameError:
    print('IMAGE / dets not available -- run Cells 5-6 first.')

# Interactive 3-D scene
try:
    pio.write_html(fig, 'scene_3d.html')
    _colab_files.download('scene_3d.html')
    print('scene_3d.html downloaded.')
except NameError:
    print('3-D figure not available -- run Cell 7 first.')

import yaml
from ultralytics import YOLO

dataset_path = "/content/My-First-Project-1"
train_images = f"{dataset_path}/train/images"

# Overwrite data.yaml with correct absolute paths
cfg = {
    "path"  : dataset_path,
    "train" : train_images,
    "val"   : train_images,   # same folder — only 5 images, no separate val
    "nc"    : 5,
    "names" : ["Ambulance", "Safety Vest", "Stethoscope", "Surgical Mask", "ceilingfan"]
}

with open(f"{dataset_path}/data.yaml", "w") as f:
    yaml.dump(cfg, f)

print("data.yaml fixed:")
print(open(f"{dataset_path}/data.yaml").read())

# Train
model = YOLO("yolov8n.pt")
results = model.train(
    data    = f"{dataset_path}/data.yaml",
    epochs  = 100,
    imgsz   = 640,
    batch   = 4,
    name    = "my_custom_model",
    project = "runs/train",
    device  = 0,
    exist_ok= True,
)

print(f"\nBest weights: {results.save_dir}/weights/best.pt")

metrics = model.val()
print(f"mAP50    : {metrics.box.map50:.3f}")
print(f"mAP50-95 : {metrics.box.map:.3f}")

from google.colab import files
files.download(f"{results.save_dir}/weights/best.pt")

from ultralytics import YOLO
import cv2, numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Verify correct model is loaded
model_path = "/content/runs/detect/runs/train/my_custom_model/weights/best.pt"
custom_model = YOLO(model_path)
print("Model classes:", custom_model.names)  # should show your 5 classes

# Upload test image
print("\nUpload image:")
up = files.upload()
name = list(up.keys())[0]
arr = np.frombuffer(list(up.values())[0], np.uint8)
img_rgb = cv2.cvtColor(cv2.imdecode(arr, cv2.IMREAD_COLOR), cv2.COLOR_BGR2RGB)

# Run with very low confidence to see ALL detections
results = custom_model(img_rgb, conf=0.01)[0]

print(f"\nTotal detections: {len(results.boxes)}")
for box in results.boxes:
    cls  = int(box.cls)
    conf = float(box.conf)
    print(f"  {custom_model.names[cls]}: {conf:.3f}")

# Draw all boxes
out = img_rgb.copy()
for box in results.boxes:
    x1,y1,x2,y2 = map(int, box.xyxy[0])
    cls   = int(box.cls)
    conf  = float(box.conf)
    label = f"{custom_model.names[cls]} {conf:.2f}"
    cv2.rectangle(out,(x1,y1),(x2,y2),(0,255,0),2)
    cv2.putText(out,label,(x1,max(y1-6,0)),
                cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,255,0),2)

plt.figure(figsize=(10,6))
plt.imshow(out)
plt.axis("off")
plt.show()

# ── Download flower dataset ────────────────────────────────────────────────
!pip install -q roboflow

from roboflow import Roboflow
import yaml, os
from ultralytics import YOLO
from google.colab import files

rf      = Roboflow(api_key="ex1Qh879W9azJCfo8Ls2")
project = rf.workspace("jayas-workspace-grrwd").project("flowers-ezwl7")
version = project.version(1)
dataset = version.download("yolov8")

dataset_path = dataset.location
print(f"Dataset path: {dataset_path}")

# ── Check what downloaded ──────────────────────────────────────────────────
for root, dirs, f in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    print(f"{'  '*level}{os.path.basename(root)}/  ({len(f)} files)")

# ── Fix data.yaml with absolute paths ─────────────────────────────────────
train_path = f"{dataset_path}/train/images"
val_path   = f"{dataset_path}/valid/images" if os.path.exists(f"{dataset_path}/valid/images") else train_path

# Read original to get class names
with open(f"{dataset_path}/data.yaml") as f:
    orig = yaml.safe_load(f)

print(f"\nClasses ({orig['nc']}): {orig['names']}")

cfg = {
    "path"  : dataset_path,
    "train" : train_path,
    "val"   : val_path,
    "nc"    : orig["nc"],
    "names" : orig["names"],
}
with open(f"{dataset_path}/data.yaml", "w") as f:
    yaml.dump(cfg, f)

print(f"Train path: {train_path}")
print(f"Val path  : {val_path}")

# ── Train ──────────────────────────────────────────────────────────────────
model = YOLO("yolov8n.pt")
results = model.train(
    data     = f"{dataset_path}/data.yaml",
    epochs   = 100,
    imgsz    = 640,
    batch    = 4,
    device   = 0,
    name     = "flower_model",
    project  = "runs/train",
    exist_ok = True,
)

FLOWER_MODEL_PATH = f"{results.save_dir}/weights/best.pt"
print(f"\nFlower model saved: {FLOWER_MODEL_PATH}")

# ── Validate ───────────────────────────────────────────────────────────────
metrics = model.val()
print(f"mAP50    : {metrics.box.map50:.3f}")
print(f"mAP50-95 : {metrics.box.map:.3f}")

# ── Download best.pt ───────────────────────────────────────────────────────
files.download(FLOWER_MODEL_PATH)

import os, yaml

# ── Check ALL flower datasets in /content ─────────────────────────────────
print("All folders in /content:")
for item in os.listdir("/content"):
    full = f"/content/{item}"
    if os.path.isdir(full):
        print(f"  {item}/")

print()

# ── Check the new dataset path ─────────────────────────────────────────────
# Roboflow names it based on project slug
possible_paths = [
    "/content/flowers-n0kd5-1",
    "/content/flowers-1",
    "/content/flowers-2",
    "/content/Flowers-1",
]

for p in possible_paths:
    if os.path.exists(p):
        train_imgs = f"{p}/train/images"
        valid_imgs = f"{p}/valid/images"
        n_train = len(os.listdir(train_imgs)) if os.path.exists(train_imgs) else 0
        n_valid = len(os.listdir(valid_imgs)) if os.path.exists(valid_imgs) else 0
        print(f"FOUND: {p}")
        print(f"  train: {n_train} images")
        print(f"  valid: {n_valid} images")
        if os.path.exists(f"{p}/data.yaml"):
            with open(f"{p}/data.yaml") as f:
                cfg = yaml.safe_load(f)
            print(f"  classes: {cfg.get('names')}")
        print()

import shutil, os
from roboflow import Roboflow
import yaml
from ultralytics import YOLO
from google.colab import files

# ── Remove old dataset ─────────────────────────────────────────────────────
if os.path.exists("/content/flowers-1"):
    shutil.rmtree("/content/flowers-1")
    print("Removed old flowers-1")

# ── Download new dataset ───────────────────────────────────────────────────
rf      = Roboflow(api_key="ex1Qh879W9azJCfo8Ls2")
project = rf.workspace("yolo-77nzg").project("flowers-n0kd5")

# Check available versions
print("Available versions:")
for v in project.versions():
    print(f"  version {v.version}  —  {v.name}")

version = project.version(4)
dataset = version.download("yolov8")

dataset_path = dataset.location
print(f"\nDownloaded to: {dataset_path}")

train_path = f"{dataset_path}/train/images"
valid_path = f"{dataset_path}/valid/images"

print(f"Train images: {len(os.listdir(train_path)) if os.path.exists(train_path) else 'MISSING'}")
print(f"Valid images: {len(os.listdir(valid_path)) if os.path.exists(valid_path) else 'MISSING'}")

with open(f"{dataset_path}/data.yaml") as f:
    orig = yaml.safe_load(f)
print(f"Classes ({orig['nc']}): {orig['names']}")

!pip install -q roboflow ultralytics

import os, yaml
from roboflow import Roboflow
from ultralytics import YOLO
from google.colab import files

# ── Re-download dataset ────────────────────────────────────────────────────
rf      = Roboflow(api_key="ex1Qh879W9azJCfo8Ls2")
project = rf.workspace("sanjayk").project("flowers-0elmu")
version = project.version(1)
dataset = version.download("yolov8")

dataset_path = dataset.location
train_path   = f"{dataset_path}/train/images"
valid_path   = f"{dataset_path}/valid/images"

with open(f"{dataset_path}/data.yaml") as f:
    orig = yaml.safe_load(f)

cfg = {
    "path"  : dataset_path,
    "train" : train_path,
    "val"   : valid_path if os.path.exists(valid_path) else train_path,
    "nc"    : orig["nc"],
    "names" : orig["names"],
}
with open(f"{dataset_path}/data.yaml", "w") as f:
    yaml.dump(cfg, f)

# ── Train ──────────────────────────────────────────────────────────────────
model = YOLO("yolov8n.pt")
results = model.train(
    data     = f"{dataset_path}/data.yaml",
    epochs   = 100,
    imgsz    = 640,
    batch    = 16,
    device   = 0,
    name     = "flower_sanjay",
    project  = "/content/runs/train",
    exist_ok = True,
)

FLOWER_MODEL_PATH = f"{results.save_dir}/weights/best.pt"
print(f"Model path: {FLOWER_MODEL_PATH}")

# ── Download to your computer so you never lose it again ──────────────────
files.download(FLOWER_MODEL_PATH)

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from ultralytics import YOLO
from google.colab import files

# ── Load model ─────────────────────────────────────────────────────────────
FLOWER_MODEL_PATH = "/content/runs/train/flower_sanjay/weights/best.pt"
flower_model = YOLO(FLOWER_MODEL_PATH)
print("Classes:", flower_model.names)

# ── Color lookup ───────────────────────────────────────────────────────────
COLOR_NAMES = {
    "Red":         (220,  20,  60),
    "Dark Red":    (139,   0,   0),
    "Pink":        (255, 105, 180),
    "Hot Pink":    (255,  20, 147),
    "Orange":      (255, 140,   0),
    "Yellow":      (255, 215,   0),
    "White":       (255, 255, 255),
    "Off White":   (240, 235, 240),
    "Purple":      (128,   0, 128),
    "Dark Purple": ( 75,   0, 130),
    "Violet":      (148,   0, 211),
    "Lavender":    (210, 190, 220),
    "Blue":        ( 30, 144, 255),
    "Light Blue":  (135, 206, 235),
    "Green":       ( 34, 139,  34),
    "Light Green": (144, 238, 144),
    "Brown":       (139,  69,  19),
    "Cream":       (255, 253, 208),
    "Peach":       (255, 218, 185),
    "Coral":       (255, 127,  80),
    "Magenta":     (255,   0, 255),
    "Gray":        (128, 128, 128),
}

def nearest_color(r, g, b):
    best, min_dist = "Unknown", float("inf")
    for name, (cr, cg, cb) in COLOR_NAMES.items():
        d = (r-cr)**2 + (g-cg)**2 + (b-cb)**2
        if d < min_dist:
            min_dist, best = d, name
    return best

# ── Upload flower image ────────────────────────────────────────────────────
print("\nUpload a flower image:")
up      = files.upload()
fname   = list(up.keys())[0]
arr     = np.frombuffer(list(up.values())[0], np.uint8)
img_rgb = cv2.cvtColor(cv2.imdecode(arr, cv2.IMREAD_COLOR), cv2.COLOR_BGR2RGB)

# ── YOLO detect ───────────────────────────────────────────────────────────
dets = flower_model(img_rgb, conf=0.5, iou=0.4)[0]
if not dets.boxes:
    dets = flower_model(img_rgb, conf=0.1, iou=0.4)[0]
    print(f"Retry conf=0.1 → {len(dets.boxes)} found")
else:
    print(f"Flowers found: {len(dets.boxes)}")

if not dets.boxes:
    print("No flower detected.")
else:
    sam_predictor.set_image(img_rgb)
    total = len(dets.boxes)
    fig, axes = plt.subplots(total, 7, figsize=(20, 5 * total))
    if total == 1:
        axes = [axes]

    for idx, box in enumerate(dets.boxes):
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cls_name = flower_model.names[int(box.cls)]
        conf     = float(box.conf)

        # SAM mask
        mask, _, _ = sam_predictor.predict(
            box=np.array([x1, y1, x2, y2], dtype=float),
            multimask_output=False,
        )
        flower_mask = mask[0].astype(bool)

        # K-Means on flower pixels only
        pixels = img_rgb[flower_mask].astype(np.float32)
        valid  = pixels[
            ~(((pixels[:,0]>245) & (pixels[:,1]>245) & (pixels[:,2]>245)) |
              ((pixels[:,0]< 20) & (pixels[:,1]< 20) & (pixels[:,2]< 20)))
        ]
        if len(valid) < 50:
            valid = pixels


        km = KMeans(n_clusters=5, n_init=10, random_state=42)
        km.fit(valid)
        centers   = km.cluster_centers_.astype(int)
        _, counts = np.unique(km.labels_, return_counts=True)
        pcts      = counts / counts.sum() * 100
        order     = np.argsort(-pcts)
        centers   = centers[order]
        pcts      = pcts[order]

        r0, g0, b0 = int(centers[0][0]), int(centers[0][1]), int(centers[0][2])
        main_color = nearest_color(r0, g0, b0)

        # Draw
        vis = img_rgb.copy()
        cv2.rectangle(vis, (x1,y1),(x2,y2),(0,255,0),3)
        cv2.putText(vis, f"{cls_name} | {main_color}",
                    (x1, max(y1-8,0)), cv2.FONT_HERSHEY_SIMPLEX, 0.8,(0,255,0),2)
        vis[flower_mask] = (vis[flower_mask]*0.5 + np.array([0,255,100])*0.5).astype(np.uint8)

        axes[idx][0].imshow(vis)
        axes[idx][0].set_title(f"{cls_name}\n{main_color}  conf={conf:.2f}", fontsize=9)
        axes[idx][0].axis("off")

        print(f"\nFlower {idx+1} [{cls_name}]  conf={conf:.2f}  → {main_color}")
        print("─" * 42)

        for i in range(5):
            r, g, b = int(centers[i][0]), int(centers[i][1]), int(centers[i][2])
            cname   = nearest_color(r, g, b)
            pct     = pcts[i]
            swatch  = np.full((80,80,3), [r,g,b], dtype=np.uint8)
            axes[idx][i+1].imshow(swatch)
            axes[idx][i+1].set_title(f"{cname}\n{pct:.1f}%\nRGB({r},{g},{b})", fontsize=8)
            axes[idx][i+1].axis("off")
            print(f"  {i+1}. {cname:<13} {pct:5.1f}%   RGB({r},{g},{b})")

    plt.suptitle("Flower Detection + Color Analysis  (YOLOv8 + SAM + K-Means)",
                 fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.show()

